docker_builder:
   env:
     USERNAME: "ENCRYPTED[!8944c2f28c831b2067a9b30b76f9d79e49df79a1c3ce3a2dbb5c67105a0cd97623e808cbfe578a35b01b5ce84997fc94!]"
     EMAIL: "ENCRYPTED[!c35915516c106c1deff4cd4990ba3996ea20535e7b782cb88c051fa1d9706db63dd027a7e8570e5ad6d1701961eb2595!]"
     PASSWORD: "ENCRYPTED[!00caa4b6a39951c2c4f7de789734a0ab010eb4fe08898bd1bbffb74a723e126030f52342fd358279c8c8cd87066990e5!]"
     DOCKERNAME: "aiko"
     DOCKERTAG: "latest"
     GITHUB: "https://github.com/AikoCute-Offical/DockerFile-Cirrus.git"
   only_if: $CIRRUS_REPO_OWNER == 'AikoCute-Offical' && $CIRRUS_BRANCH == 'aiko'
   skip: $CIRRUS_BRANCH != 'aiko'
   Docker_script:
     - git clone -b $DOCKERNAME --single-branch $GITHUB Dockerfile && cd Dockerfile
     - docker login -u $USERNAME -p $PASSWORD
     - docker build -t $DOCKERNAME . 
     - docker tag $DOCKERNAME:$DOCKERTAG $USERNAME/$DOCKERNAME:$DOCKERTAG
     - docker push $USERNAME/$DOCKERNAME:$DOCKERTAG